quarkus:
  application:
    name: telemetry-client

  log:
    level: INFO
    category:
      "com.example":
        level: DEBUG

  # Native compilation settings
  native:
    container-build: true
    container-runtime: docker

  # Metrics configuration
  micrometer:
    export:
      json:
        enabled: true
        path: /metrics


# Configure the RabbitMQ broker credentials
rabbitmq:
  host: ${RABBITMQ_HOST:localhost}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME:admin}
  password: ${RABBITMQ_PASSWORD:admin123}

mp:
  messaging:
    # Configure the outgoing channel (producer)
    outgoing:
      telemetry-out:
        connector: smallrye-rabbitmq
        exchange: telemetry-exchange
        routing-key: telemetry-data
        durable: true
    # Configure the incoming channel (consumer)
    incoming:
      telemetry-in:
        connector: smallrye-rabbitmq
        queue: telemetry-queue
        exchange: telemetry-exchange
        routing-key: telemetry-data
        durable: true

# Custom configuration properties
device:
  id: ${DEVICE_ID:device-001}

