services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - telemetry-ingestion-service
    networks:
      - elder-spy-network

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=telemetry-org
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - elder-spy-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "15672:15672"  # Management UI port
    depends_on:
      - influxdb
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
    networks:
      - elder-spy-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 30s
      timeout: 10s
      retries: 5

  telemetry-client:
    build:
      context: ./backend/services
      dockerfile: ./telemetry-client/src/main/docker/Dockerfile.jvm
    container_name: telemetry-client
    ports:
      - "9900:9900"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin123
    networks:
      - elder-spy-network
    restart: on-failure

  telemetry-ingestion-service:
    build:
      context: ./backend/services
      dockerfile: ./telemetry-ingestion-service/src/main/docker/Dockerfile.jvm
    container_name: telemetry-ingestion-service
    ports:
      - "9901:9901"
    depends_on:
      - rabbitmq
      - influxdb
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin123
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_ORG=telemetry-org
      - INFLUXDB_BUCKET=telemetry-bucket
    networks:
      - elder-spy-network
    restart: on-failure

  telemetry-analyser-service:
    build:
      context: ./backend/services
      dockerfile: ./telemetry-analyser-service/src/main/docker/Dockerfile.jvm
    container_name: telemetry-analyser-service
    ports:
      - "9902:9902"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_ORG=telemetry-org
      - INFLUXDB_BUCKET=telemetry-bucket
    networks:
      - elder-spy-network
    restart: on-failure

  alerting-service:
    build:
      context: ./backend/services
      dockerfile: ./alerting-service/src/main/docker/Dockerfile.jvm
    container_name: alerting-service
    ports:
      - "9903:9903"
    networks:
      - elder-spy-network
    restart: on-failure

  gsm-gateway:
    build:
      context: ./backend/services
      dockerfile: ./gsm-gateway/src/main/docker/Dockerfile.jvm
    container_name: gsm-gateway
    ports:
      - "9904:9904"
    depends_on:
      - alerting-service
    environment:
      - ALERTING_SERVICE_HOST=alerting-service
      - ALERTING_SERVICE_PORT=9903
    networks:
      - elder-spy-network
    restart: on-failure

networks:
  elder-spy-network:
    driver: bridge

volumes:
  grafana-data:
  influxdb-data: