services:
  nanomq:
    image: emqx/nanomq:latest-full

    container_name: nanomq
    ports:
      - "1883:1883"    # MQTT
      - "8083:8083"    # WebSockets
      - "8883:8883"    # Secure MQTT over SSL/TLS
    volumes:
      - ./nanomq.conf:/etc/nanomq.conf  # Mount your NanoMQ configuration
      - ./data:/tmp/sqlite_rule_all.db
    networks:
      - iot_network

  nodered :
    build: ../sensors
    image: nodered/node-red
    environment:
      - NODE_RED_ENABLE_PROJECTS=false
    ports:
      - "1880:1880"
    restart: always
    networks:
      - iot_network

  # other future services

networks:
  iot_network:
    driver: bridge

volumes:
  node_red_data:
