services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "4000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-provisioning:/etc/grafana/provisioning
    depends_on:
      - telemetry-ingestion-ms
    networks:
      - elder-spy-network

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
      - DOCKER_INFLUXDB_INIT_ORG=telemetry-org
      - DOCKER_INFLUXDB_INIT_BUCKET=telemetry-bucket
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - elder-spy-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # AMQP protocol port
      - "1883:1883"  # MQTT protocol port
      - "15672:15672"  # Management UI port
    depends_on:
      - influxdb
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin123
      - RABBITMQ_LOG_LEVEL=debug    # Options: debug, info, warning, error
      - RABBITMQ_LOGS=-             # Output logs to stdout (container logs)
      - RABBITMQ_LOG_CHANNEL_LEVEL=debug
      - RABBITMQ_LOG_CONNECTION_LEVEL=info
      - RABBITMQ_LOG_QUEUE_LEVEL=debug
    volumes:
      - ./rabbitmq/rabbitmq_enabled_plugins:/etc/rabbitmq/enabled_plugins
    networks:
      - elder-spy-network
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "check_port_connectivity" ]
      interval: 30s
      timeout: 10s
      retries: 5

  telemetry-client-ms:
    image: telemetry-client-ms:latest
    build:
      context: ./services
      dockerfile: telemetry-client/src/main/docker/Dockerfile.jvm
    container_name: telemetry-client-ms
    ports:
      - "9900:9900"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin123
    networks:
      - elder-spy-network
    restart: on-failure

  telemetry-ingestion-ms:
    image: telemetry-ingestion-ms:latest
    build:
      context: ./services
      dockerfile: telemetry-ingestion-service/src/main/docker/Dockerfile.jvm
    container_name: telemetry-ingestion-ms
    ports:
      - "9901:9901"
    depends_on:
      - rabbitmq
      - influxdb
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin123
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_ORG=telemetry-org
      - INFLUXDB_BUCKET=telemetry-bucket
    networks:
      - elder-spy-network
    restart: on-failure

  telemetry-analyser-ms:
    image: telemetry-analyser-ms:latest
    build:
      context: ./services
      dockerfile: telemetry-analyser-service/src/main/docker/Dockerfile.jvm
    container_name: telemetry-analyser-ms
    ports:
      - "9902:9902"
    depends_on:
      - influxdb
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-auth-token
      - INFLUXDB_ORG=telemetry-org
      - INFLUXDB_BUCKET=telemetry-bucket
      - ALERTING_SERVICE_HOST=alerting-ms
      - ALERTING_SERVICE_PORT=9903
    networks:
      - elder-spy-network
    restart: on-failure

  alerting-ms:
    image: alerting-ms:latest
    build:
      context: ./services
      dockerfile: alerting-service/src/main/docker/Dockerfile.jvm
    container_name: alerting-ms
    environment:
      - GSM_GATEWAY_HOST=gsm-gateway-ms
      - GSM_GATEWAY_PORT=9904
    ports:
      - "9903:9903"
    networks:
      - elder-spy-network
    restart: on-failure

  gsm-gateway-ms:
    image: gsm-gateway-ms:latest
    build:
      context: ./services
      dockerfile: gsm-gateway/src/main/docker/Dockerfile.jvm
    container_name: gsm-gateway-ms
    ports:
      - "9904:9904"
    depends_on:
      - alerting-ms
    env_file:
      - ./services/gsm-gateway/.env
    environment:
      - ALERTING_SERVICE_HOST=alerting-ms
      - ALERTING_SERVICE_PORT=9903
    networks:
      - elder-spy-network
    restart: on-failure

networks:
  elder-spy-network:
    driver: bridge

volumes:
  grafana-data:
  influxdb-data: