apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemetry-ingestion-deployment
  namespace: elderspy-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemetry-ingestion
  template:
    metadata:
      labels:
        app: telemetry-ingestion
    spec:
      containers:
        - name: telemetry-ingestion
          image: telemetry-ingestion-ms:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9901
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq.elderspy-ns.svc.cluster.local"
            - name: RABBITMQ_PORT
              value: "1883"
            - name: RABBITMQ_USERNAME
              value: "admin"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-secrets
                  key: RABBITMQ_PASSWORD
            - name: INFLUXDB_URL
              value: "http://influxdb.elderspy-ns.svc.cluster.local:8086"
            - name: INFLUXDB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: influxdb-secrets
                  key: DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
            - name: INFLUXDB_ORG
              valueFrom:
                configMapKeyRef:
                  name: influxdb-config
                  key: DOCKER_INFLUXDB_INIT_ORG
            - name: INFLUXDB_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: influxdb-config
                  key: DOCKER_INFLUXDB_INIT_BUCKET
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

