apiVersion: v1
kind: Service
metadata:
  name: telemetry-ingestion-service
spec:
  selector:
    app: telemetry-ingestion
  ports:
    - protocol: TCP
      port: 9901
      targetPort: 9901
  type: LoadBalancer