apiVersion: v1
kind: Service
metadata:
  name: telemetry-ingestion-service
  namespace: elderspy-ns
spec:
  type: NodePort
  selector:
    app: telemetry-ingestion
  ports:
    - protocol: TCP
      port: 9901
      targetPort: 9901
      nodePort: 30901
