# File: storage-service/src/main/resources/application.yml
quarkus:
  application:
    name: telemetry-ingestion-service

  log:
    level: INFO
    category:
      "com.polytech":
        level: DEBUG

  # Native compilation settings
  native:
    container-build: true
    container-runtime: docker

  # Metrics configuration
  micrometer:
    enabled: true
    export:
      json:
        enabled: true
        path: /metrics

# Custom configuration properties
influxdb:
  url: ${INFLUXDB_URL:http://localhost:8086}
  token: ${INFLUXDB_TOKEN:your-super-secret-auth-token}
  org: ${INFLUXDB_ORG:telemetry-org}
  bucket: ${INFLUXDB_BUCKET:telemetry-bucket}

rabbitmq:
  host: ${RABBITMQ_HOST:rabbitmq}
  port: ${RABBITMQ_PORT:5672}
  username: ${RABBITMQ_USERNAME:admin}
  password: ${RABBITMQ_PASSWORD:admin123}

