spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092 # Default for local development
      group-id: demo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.polytech.model"
  application:
    name: kafka-consumer
server:
  port: 8082

---
spring:
  config:
    activate:
      on-profile: docker
  kafka:
    consumer:
      bootstrap-servers: kafka:9092 # Use container name in Docker network
      group-id: demo-group
      auto-offset-reset: earliest